### ISSUE TITLE
Unify platform models across applications

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumukit-platform#12]
_This issue will track changes of `feature-unified-platform-model` branches across `login`, `platform`, `laboratory`, `classroom-api` and `bibliotheca`_

Currently, there are several inconsistencies among the mumuki applications and the platform models - missing or extra fields, missing course entity, duplicated behavior, and so on.

Before release mumukit 5 - since it has a dramatic impact in the office application, which is being deprecated and merged into laboratory - we should:

- [x] Ensure that User, Organization and Course models do only have cache semantics and no extra information. Ensure we can actually drop them and reimport them and everything just works fine.
   - [x]  Bibliotheca
      - [x]   Organization: OK
      - [x]  User: OK
      - [x]   Course: -
   - [x]   Laboratory
     - [x]   Organization: NOK
     - [x]   User:  NOK
     - [x]   Course: -
   - [x]   Classroom
     - [x]   Organization: OK (if missing fields are added)
     - [x]  User: OK (if missing fields are added)
     - [x] Course: Must remove the `uid` field

- [x] Alter laboratory's  organization. See https://github.com/mumuki/mumukit-platform/issues/12#issuecomment-375668107
- [x] Alter laboratory's user. See https://github.com/mumuki/mumukit-platform/issues/12#issuecomment-375668107
- [x] Alter classroom's organization.  See https://github.com/mumuki/mumukit-platform/issues/12#issuecomment-375668649
- [x] Alter classroom's user. See https://github.com/mumuki/mumukit-platform/issues/12#issuecomment-375668649
- [x] Add `Course` model into laboratory
- [x] Alter classroom's course model
- [x] Alter bibliotheca's organization  model
- [x] Move notification code into `platform`
- [x] Ensure that platform notifications are used within laboratory
- [x] Ensure that platform notifications are used within classroom
- [x] Merge organizations Create and Update events

**Comment by flbulgarelli** [comment]
## Organization's laboratory review

```
Event should be modified:
    t.text "settings", default: "{}", null: false
    t.text "theme", default: "{}", null: false
    t.text "profile", default: "{}", null: false

Should be droped from db:
    t.integer "book_ids", default: [], array: true

Timestamps:
    t.datetime "created_at"
    t.datetime "updated_at"

Synce'd fields:
    t.integer "book_id"
      book: book.slug,

    t.string "name"
      name: name,
```

**Comment by flbulgarelli** [comment]
## Classroom's laboratory review

```
Remove:
    "icon" : "/logo-alt.png",
    "socialBigButtons" : true,
    "disableResetAction" : false

Nest settings, theme, profile.
```

**Comment by flbulgarelli** [comment]
Done.
